# https://travis-ci.org/spyder-ide/spyder

language: python
dist: trusty
sudo: false

matrix:
  include:
    - python: "2.7"
      env: USE_PYQT=pyqt4
      os: linux
    - python: "2.7"
      env: USE_PYQT=pyqt5
      os: linux
    - python: "3.5"
      env: USE_PYQT=pyqt4
      os: linux
    # This slot runs our tests only with pip packages
    - python: "3.5"
      env: USE_PYQT=pyqt5
      os: linux
    - python: "3.6"
      env: USE_PYQT=pyqt5
      os: linux

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - ./continuous_integration/travis/install.sh;
  - ./continuous_integration/travis/install-qt.sh;

script:
  - ./continuous_integration/travis/runtests.sh || ./continuous_integration/travis/runtests.sh || ./continuous_integration/travis/runtests.sh;

after_success:
  - export PATH="$HOME/miniconda/bin:$PATH" && source activate test && coveralls
